### ISSUE TITLE
Creating S3 replication for existing buckets

### ISSUE THREAD

**Issue by dushyant03** [LeapBeyond/terraform-s3-replication#1]
Hi @TheBellman,

This repo is very helpful, but i just wanted to know how can this repo be used for existing source and destination buckets? Substituting S3 bucket ARN's would work?

Dushyant

**Comment by TheBellman** [comment]
More or less - you certainly can add your own ARNs, however to run it out of the box you might need to also set up terraform and the terraform backend.
